### ISSUE TITLE
[SambaNas] Autmount error if reference an hassos disk

### ISSUE THREAD

**Issue by dianlight** [dianlight/hassio-addons#124]
Here it is.
```
workgroup: workgroup
username: "!secret samba_share_username"
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - fe80::/10
automount: false
moredisks:
  - hassos-data
available_disks_log: false
medialibrary:
  enable: false
  ssh_private_key: <YOU SUPER SECRET PRIVATE KEY>
veto_files:
  - .DS_Store
  - Thumbs.db
  - icon?
  - "@eaDir"
compatibility_mode: false
wsdd2: false
mqtt_use_legacy_entities: false
autodiscovery: {}
other_users: []
acl: []
interfaces: []
password: "!secret samba_share_password"
mqtt_enable: false
```

_Originally posted by @Krocko in https://github.com/dianlight/hassio-addons/issues/121#issuecomment-1413239629_
