### ISSUE TITLE
[Samba NAS] Fail to start on 9.3.0-nas3

### ISSUE THREAD

**Issue by marciogranzotto** [dianlight/hassio-addons#13]
I'm getting the following error dialog after updating the add-on and hitting Start:

```
Failed to start addon

500 Server Error: Internal Server Error ("error while creating mount source path '/sys/firmware/devicetree/base': mkdir /sys/firmware/devicetree: operation not permitted")
```

Supervisor log:
```
20-10-23 17:13:08 INFO (MainThread) [supervisor.addons] Add-on '1a32f091_sambanas' successfully updated
20-10-23 17:13:08 WARNING (SyncWorker_4) [supervisor.docker.addon] Samba NAS running with disabled protected mode!
20-10-23 17:13:08 ERROR (SyncWorker_4) [supervisor.docker] Can't start addon_1a32f091_sambanas: 500 Server Error: Internal Server Error ("error while creating mount source path '/sys/firmware/devicetree/base': mkdir /sys/firmware/devicetree: operation not permitted")
20-10-23 17:13:10 WARNING (SyncWorker_1) [supervisor.docker.addon] Samba NAS running with disabled protected mode!
20-10-23 17:13:10 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_1a32f091_sambanas application
20-10-23 17:13:10 ERROR (SyncWorker_1) [supervisor.docker] Can't start addon_1a32f091_sambanas: 500 Server Error: Internal Server Error ("error while creating mount source path '/sys/firmware/devicetree/base': mkdir /sys/firmware/devicetree: operation not permitted")
20-10-23 17:15:30 INFO (MainThread) [supervisor.snapshots] Found 2 snapshot files
```

If I restore my snapshot of `9.3.0-nas2` it starts normally, so I think something got broken on the update.
Here's by `9.3.0-nas2` log:
![image](https://user-images.githubusercontent.com/11080704/97033728-2d771f00-153a-11eb-9c9f-4849bb4a6f3c.png)

Here's my add-on config:
```yaml
workgroup: WORKGROUP
username: homeassistant
password: 'my-secret-password'
interface: ''
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 192.168.1.1/16
  - 'fe80::/10'
moredisks:
  - wd-drive
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
autodiscovery: {}
```

I'm running HassOS.
Supervisor: 249
HassOS 4.15
Home Assistant 0.116.4

Please let me know if you need more info.

**Comment by dianlight** [comment]
The problem is related to the `devicetree` option in config.  
For now I can remove because is related to a future implementation to allow the addon to work in **protected mode**.

I need to known why you have the problem. What is your platform? (Rpi3, Rpi4, VBox ... etc )

L.

**Comment by marciogranzotto** [comment]
@dianlight I'm using a core i3 Intel NUC 8

![image](https://user-images.githubusercontent.com/11080704/97053167-bef58980-1558-11eb-8a1d-089290ab9a80.png)

Supervisor "hardware" output:
```
serial:
  - /dev/ttyUSB0
  - >-
    /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
  - /dev/ttyS0
  - /dev/ttyS1
  - /dev/ttyS2
  - /dev/ttyS3
input:
  - 'HDA Intel PCH HDMI/DP,pcm=9'
  - Video Bus
  - 'HDA Intel PCH HDMI/DP,pcm=10'
  - HDA Intel PCH Mic
  - Power Button
  - HDA Intel PCH Front Headphone
  - 'HDA Intel PCH HDMI/DP,pcm=8'
  - 'HDA Intel PCH HDMI/DP,pcm=7'
  - 'HDA Intel PCH HDMI/DP,pcm=3'
  - Sleep Button
disk: []
gpio: []
usb:
  - /dev/bus/usb/001/001
  - /dev/bus/usb/001/003
  - /dev/bus/usb/001/002
  - /dev/bus/usb/002/001
  - /dev/bus/usb/002/002
audio:
  '0':
    name: HDA-Intel - HDA Intel PCH
    type: PCH
    devices:
      - chan_id: '0'
        chan_type: digital audio playback
      - chan_id: '0'
        chan_type: digital audio capture
      - chan_id: '3'
        chan_type: digital audio playback
      - chan_id: '7'
        chan_type: digital audio playback
      - chan_id: '8'
        chan_type: digital audio playback
      - chan_id: '9'
        chan_type: digital audio playback
      - chan_id: '0'
        chan_type: hardware dependent
      - chan_id: '2'
        chan_type: hardware dependent

```
