### ISSUE TITLE
❓ [Samba NAS] other_users running into NT_STATUS_ACCESS_DENIED 

### ISSUE THREAD

**Issue by Selovert** [dianlight/hassio-addons#257]
### Addon

SambaNAS

### Your request

# What's going on

Having trouble connecting as a non-master user to shares. Hoping it's just some obvious thing I'm missing! 

Details:
- no problem connecting as the master user to either share (fern/sarahbackup)
- using this path on a mac to connect as the other user: smb://sarah@192.168.0.100
  - using the same computer to connect as tassilo and sarah
- both mounted shares are ext4

# Config
```yaml
workgroup: WORKGROUP
username: tassilo
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 169.254.0.0/16
  - fe80::/10
  - fc00::/7
automount: true
moredisks: []
mountoptions:
  - nosuid
  - relatime
  - noexec
available_disks_log: true
medialibrary:
  enable: false
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: true
recyle_bin_enabled: false
wsdd2: false
mqtt_nexgen_entities: false
autodiscovery: {}
other_users:
  - username: sarah
    password: ******
acl:
  - share: FERN
    timemachine: true
  - share: SARAHBACKUP
    timemachine: true
    users:
      - sarah
interfaces: []
password: ******
```

# Log
```
s6-rc: info: service init-samba: starting
s6-rc: info: service hd-idle: starting
s6-rc: info: service hd-idle successfully started
[07:46:13] INFO: Hostname: basilio
[07:46:13] INFO: Interfaces: wlp1s0 eno1 
[07:46:13] INFO: Docker Interface: hassio 172.30.32.0/23
[07:46:13] INFO: Enabling S.M.A.R.T for /dev/sda
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.6.54-haos] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF ENABLE/DISABLE COMMANDS SECTION ===
SMART Enabled.
SMART Attribute Autosave Enabled.
SMART Enable Automatic Offline failed: scsi error badly formed scsi parameters


[07:46:13] INFO: Enabling S.M.A.R.T for /dev/sdb
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.6.54-haos] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user tassilo.
=== START OF ENABLE/DISABLE COMMANDS SECTION ===
SMART Enabled.
SMART Attribute Autosave Enabled.
SMART Automatic Offline Testing Enabled every four hours.

[07:46:13] INFO: Enabling S.M.A.R.T for /dev/sdc
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.6.54-haos] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

Added user sarah.
---------------------------------------------------
[07:46:13] INFO: Exposed Disks Summary:
[CONFIG]                path = /homeassistant # TM:false#
[ADDONS]                path = /addons # TM:false#
[SSL]                   path = /ssl # TM:false#
[SHARE]                 path = /share # TM:false#
[BACKUP]                path = /backup # TM:false#
[MEDIA]                 path = /media # TM:false#
[ADDON_CONFIGS]         path = /addon_configs # TM:false#
[FERN]                  path = /mnt/Fern # TM:true#
[SARAHBACKUP]           path = /mnt/sarahbackup # TM:true#
---------------------------------------------------
s6-rc: info: service init-samba successfully started
s6-rc: info: service init-mqtt: starting
s6-rc: info: service wsdd: starting
s6-rc: info: service smbd: starting
s6-rc: info: service nmbd: starting
s6-rc: info: service avahi: starting
s6-rc: info: service wsdd successfully started
s6-rc: info: service smbd successfully started
s6-rc: info: service nmbd successfully started
s6-rc: info: service cifs-supervisor-mount: starting
s6-rc: info: service avahi successfully started
s6-rc: info: service cifs-supervisor-mount successfully started
[07:46:13] INFO: Starting the AVAHI for basilio...
nmbd version 4.18.9 started.
Copyright Andrew Tridgell and the Samba Team 1992-2023
Waiting for daemon ...
smbd version 4.18.9 started.
Copyright Andrew Tridgell and the Samba Team 1992-2023
[07:46:13] INFO: MQTT support not enabled in config
s6-rc: info: service init-mqtt successfully started
s6-rc: info: service mqtt-disk-handler: starting
INFO: Profiling support unavailable in this build.
[07:46:13] INFO: Starting the wsdd daemon for WORKGROUP/basilio...
s6-rc: info: service mqtt-disk-handler successfully started
s6-rc: info: service mqtt-handler: starting
s6-rc: info: service mqtt-handler successfully started
[07:46:13] INFO: Interfaces: -i wlp1s0 -i eno1 
=== START OF ENABLE/DISABLE COMMANDS SECTION ===
SMART Enabled.
SMART Attribute Autosave Enabled.
SMART Automatic Offline Testing Enabled every four hours.
2024-11-03 07:46:13,717:wsdd INFO(pid 401): using pre-defined UUID cb6a33a0-b841-531d-a34e-09ecec492eb1
2024-11-03 07:46:13,719:wsdd INFO(pid 401): joined multicast group 239.255.255.250 on 192.168.0.100%eno1
2024-11-03 07:46:13,721:wsdd INFO(pid 401): scheduling Hello message via eno1 to 239.255.255.250%eno1
2024-11-03 07:46:13,804:wsdd INFO(pid 401): joined multicast group [ff02::c] on fe80::8a05:69ab:8463:787a%eno1
2024-11-03 07:46:13,806:wsdd INFO(pid 401): scheduling Hello message via eno1 to ff02::c%eno1

s6-rc: info: service init-smartd successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
*****

Samba name server BASILIO is now a local master browser for workgroup WORKGROUP on subnet 192.168.0.100

*****
*****

Samba name server BASILIO is now a local master browser for workgroup WORKGROUP on subnet 172.30.32.1

*****
create_connection_session_info: user 'sarah' (from session setup) not permitted to access this share (SARAHBACKUP)
create_connection_session_info failed: NT_STATUS_ACCESS_DENIED
create_connection_session_info: user 'sarah' (from session setup) not permitted to access this share (SARAHBACKUP)
create_connection_session_info failed: NT_STATUS_ACCESS_DENIED
parse_dfs_path_strict: can't parse hostname from path \192.168.0.100
```
